name: ServerStats
version: '${project.version}'
main: com.scottverhage.serverstats.ServerStats
api-version: '1.20'
load: STARTUP
authors: [Scottmobiel]
description: Toont server statistieken.
website: https://wanneerwordikgevaccineerd.nl/
